# Generated by Django 4.2.14 on 2024-07-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('game', models.CharField(choices=[('pong', 'Pong'), ('brick', 'Brick')], max_length=10, verbose_name='Game')),
                ('state', models.CharField(choices=[('created', 'Created'), ('ongoing', 'On-going'), ('ended', 'Ended'), ('canceled', 'Canceled')], max_length=10, verbose_name='State')),
                ('kind', models.CharField(choices=[('single', 'Single'), ('rematch', 'Rematch'), ('tournament', 'Tournament')], max_length=10, verbose_name='Kind')),
                ('scoreboard', models.JSONField(default=dict, verbose_name='Scoreboard')),
                ('modifiers', models.JSONField(default=dict, verbose_name='Modifiers')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.match', verbose_name='Next match')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL, verbose_name='session')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('dataset'), models.Model),
        ),
    ]
