# Generated by Django 4.2.14 on 2024-07-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="tournament_uuid",
            field=models.UUIDField(blank=True, null=True, verbose_name="Id Tournament"),
        ),
        migrations.AlterField(
            model_name="match",
            name="modifiers",
            field=models.JSONField(blank=True, default=dict, verbose_name="Modifiers"),
        ),
        migrations.AlterField(
            model_name="match",
            name="scoreboard",
            field=models.JSONField(blank=True, default=dict, verbose_name="Scoreboard"),
        ),
        migrations.AlterField(
            model_name="match",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("ended", "Ended"),
                    ("canceled", "Canceled"),
                ],
                max_length=10,
                verbose_name="State",
            ),
        ),
    ]
