# Generated by Django 4.2.14 on 2024-08-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_game_alter_match_modifiers_and_more'),
        ('game', '0003_alter_match_modifiers_alter_match_scoreboard'),
    ]

    operations = [
    ]
