{
 "title": "Dashboard com prometheus e grafana",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes/(1024*1024)",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "Log do elastic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_document" }
     ],
     "query": "log.file.path:\"/usr/share/filebeat/app/app.log\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Usuarios cadastrados",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT username, date_joined FROM auth_user LIMIT 50 "
    }
   ]
  }
 ]
}