apiVersion: 1
groups:
    - orgId: 1
      name: alert
      folder: alert
      interval: 10s
      rules:
        - uid: edundnjiui874f
          title: Alert
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: bdrazo17dkr9ca
              model:
                disableTextWrap: false
                editorMode: builder
                exemplar: false
                expr: up{instance="app:8000"}
                format: time_series
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                interval: ""
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ft_trancendence
          panelId: 10
          noDataState: Alerting
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: ft_trancendence
            __panelId__: "10"
          isPaused: false
