filebeat.inputs:
- type: log
  enabled: true
  paths:
    - app/*.log
  fields:
    level: info
    event.dataset: transcendence
  fields_under_root: true

processors:
- add_docker_metadata: ~

setup:
  kibana:
    host: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
  template:
    name: filebeat-*
    pattern: filebeat-*

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  index: filebeat-*
  ssl:
    enabled: false
