networks:
  dev:
    driver: bridge

services:
  dev-db:
    image: postgres:15
    container_name: postgres
    restart: on-failure
    networks:
      - dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    networks:
      - dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:80
    restart: on-failure
