filebeat.inputs:
- type: log
  enabled: true
  paths:
    - app/*.log
  fields:
    level: info
    event.dataset: ft_transcendence
  fields_under_root: true

#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD} 

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}