# Generated by Django 4.2.14 on 2024-07-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matches_won',
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Intra url'),
        ),
    ]
